<a href="https://colab.research.google.com/github/wkabbani/pytorch-playground/blob/main/00_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. Fundamentals

In [1]:
import torch
torch.__version__

'1.13.0+cu116'

## 00.01. Creating Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# check the number of dimensions
scalar.ndim

0

In [6]:
# get python number from tensor
scalar.item()

7

In [8]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# matrix
matrix = torch.tensor([[1,2,], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [12]:
matrix.ndim

2

In [14]:
# how the numbers in the tensor are arranged
matrix.shape

torch.Size([2, 2])

In [15]:
tensor = torch.tensor([[[1,2], [3,4], [5,6]]])
tensor

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 2])

## 00.02. Random Tensors

In [18]:
random_tensor = torch.rand(size=(3,4))
random_tensor

tensor([[0.1867, 0.8419, 0.1495, 0.2904],
        [0.1369, 0.6049, 0.0985, 0.8573],
        [0.8494, 0.4066, 0.5451, 0.4594]])

In [19]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [20]:
random_img_size_tensor = torch.rand(size=(224, 224, 3))
random_img_size_tensor.ndim, random_img_size_tensor.shape

(3, torch.Size([224, 224, 3]))

## 00.03. Zeros and Ones

In [22]:
zeros = torch.zeros(size=(3, 3, 3))
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [23]:
zeros.ndim, zeros.shape

(3, torch.Size([3, 3, 3]))

In [24]:
ones = torch.ones(size=(2,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [25]:
ones.ndim, ones.shape

(2, torch.Size([2, 5]))

In [28]:
zeros_like = torch.zeros_like(ones)
zeros_like

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [29]:
ones_like = torch.ones_like(zeros)
ones_like

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

## 00.04. Creating a range

In [26]:
range_tensor = torch.arange(start=-0.5, end=0.5, step=0.1)
range_tensor

tensor([-5.0000e-01, -4.0000e-01, -3.0000e-01, -2.0000e-01, -1.0000e-01,
         2.7756e-17,  1.0000e-01,  2.0000e-01,  3.0000e-01,  4.0000e-01])

In [27]:
range_tensor.ndim, range_tensor.shape

(1, torch.Size([10]))

## 00.05. Data Types

In [31]:
float_32_tensor = torch.tensor([7,6], dtype=torch.float64, device='cpu', requires_grad=True)
float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.shape

(torch.float64, device(type='cpu'), torch.Size([2]))

## 00.06. Basic Operations

In [33]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor - 10

tensor([-9, -8, -7])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [37]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [39]:
# element-wise
tensor * tensor

tensor([1, 4, 9])

In [40]:
tensor + tensor

tensor([2, 4, 6])

In [41]:
tensor - tensor

tensor([0, 0, 0])

In [42]:
tensor / tensor

tensor([1., 1., 1.])

## 00.07. Matrix Multiplication

In [43]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [44]:
tensor * tensor

tensor([1, 4, 9])

In [45]:
torch.matmul(tensor, tensor)

tensor(14)

In [46]:
tensor @ tensor

tensor(14)

In [47]:
a = torch.tensor([[1,2], [2,3], [3,4]], dtype=torch.float32, device='cpu')
b = torch.tensor([[1,2], [2,3], [3,4]], dtype=torch.float32, device='cpu')

In [48]:
a * b

tensor([[ 1.,  4.],
        [ 4.,  9.],
        [ 9., 16.]])

In [51]:
a

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])

In [52]:
b

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])

In [53]:
a.T

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [54]:
b.T

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [55]:
a @ b.T

tensor([[ 5.,  8., 11.],
        [ 8., 13., 18.],
        [11., 18., 25.]])

In [56]:
torch.mm(a, b.T)

tensor([[ 5.,  8., 11.],
        [ 8., 13., 18.],
        [11., 18., 25.]])

In [59]:
torch.manual_seed(77)
linear = torch.nn.Linear(in_features=2, out_features=6)
linear(a)

tensor([[-0.9080,  0.4442, -0.0332,  0.9112, -0.6741,  0.7107],
        [-1.5054,  0.2555,  0.2592,  1.6542, -1.1146,  1.1461],
        [-2.1028,  0.0668,  0.5516,  2.3973, -1.5551,  1.5816]],
       grad_fn=<AddmmBackward0>)

## 00.08. Aggregation

In [66]:
tensor = torch.tensor([[1,2,3],[-1,0,100]])
tensor, tensor.dtype

(tensor([[  1,   2,   3],
         [ -1,   0, 100]]), torch.int64)

In [63]:
tensor.min()

tensor(-1)

In [64]:
tensor.max()

tensor(100)

In [67]:
tensor.type(torch.float32).mean()

tensor(17.5000)

In [68]:
tensor.sum()

tensor(105)

In [70]:
torch.min(tensor), torch.max(tensor), torch.sum(tensor), torch.mean(tensor.type(torch.float32))

(tensor(-1), tensor(100), tensor(105), tensor(17.5000))

In [71]:
torch.argmax(tensor)

tensor(5)

In [72]:
torch.argmin(tensor)

tensor(3)

tensor([[  1,   2,   3],
        [ -1,   0, 100]])

## 00.09. Manipulating Tensors

In [77]:
tensor = torch.arange(1.,10.)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [78]:
tensor.ndim, tensor.shape

(1, torch.Size([9]))

In [80]:
t1 = torch.reshape(tensor, shape=(1,9))
t1, t1.ndim, t1.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), 2, torch.Size([1, 9]))

In [88]:
v1 = tensor.view(1,9)
v1, v1.ndim, v1.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), 2, torch.Size([1, 9]))

In [94]:
torch.stack([tensor, tensor, tensor], dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [95]:
torch.stack([tensor, tensor, tensor], dim=1)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [7., 7., 7.],
        [8., 8., 8.],
        [9., 9., 9.]])

In [96]:
t1.shape

torch.Size([1, 9])

In [99]:
t1.squeeze().shape

torch.Size([9])

In [107]:
t2 = t1.unsqueeze(dim=2)
t2, t2.shape

(tensor([[[1.],
          [2.],
          [3.],
          [4.],
          [5.],
          [6.],
          [7.],
          [8.],
          [9.]]]), torch.Size([1, 9, 1]))

In [110]:
x = torch.rand(size=(2,2,3))
x, x.shape

(tensor([[[0.5699, 0.7500, 0.8245],
          [0.8572, 0.3245, 0.6603]],
 
         [[0.5040, 0.6164, 0.2546],
          [0.4183, 0.7967, 0.8742]]]), torch.Size([2, 2, 3]))

In [112]:
x.permute(dims=(2, 0, 1)).shape

torch.Size([3, 2, 2])

## 00.10. Indexing

In [113]:
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [118]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [119]:
tensor[0][0]

tensor([1, 2, 3])

In [120]:
tensor[0][0][0]

tensor(1)

In [121]:
tensor[:,0]

tensor([[1, 2, 3]])

In [123]:
tensor[:, 1]

tensor([[4, 5, 6]])

In [124]:
tensor[:, :, 0]

tensor([[1, 4, 7]])

In [125]:
tensor[:, 1, 1]

tensor([5])

In [128]:
tensor[0,0,0], tensor[0][0][0], tensor[:,0,0]

(tensor(1), tensor(1), tensor([1]))

In [131]:
tensor[0, 0], tensor[0, 0, :]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

## 00.11. Pytorch and NumPy

In [132]:
import numpy as np
array = np.arange(0,10)
tensor = torch.from_numpy(array)
array, tensor

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [133]:
tensor.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 00.12. GPU

In [134]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [135]:
torch.cuda.is_available()

False

In [136]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [137]:
torch.cuda.device_count()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

In [138]:
tensor = torch.arange(1,10).to(device)
tensor.device

device(type='cpu')

In [140]:
tensor = tensor.cpu()
tensor.device

device(type='cpu')